SELECT S.NAME, S.ADDRESS
FROM STUDIO S JOIN MOVIE M ON S.NAME = M.STUDIONAME
WHERE M.INCOLOR='Y'
INTERSECT
SELECT S.NAME, S.ADDRESS
FROM STUDIO S JOIN MOVIE M ON S.NAME = M.STUDIONAME
WHERE M.INCOLOR='N'
ORDER BY ADDRESS;

SELECT DISTINCT S.NAME, S.ADDRESS
FROM STUDIO S JOIN MOVIE M on S.NAME = M.STUDIONAME
WHERE M.INCOLOR='Y' AND S.NAME IN (SELECT S.NAME
                                   FROM STUDIO S
                                   JOIN MOVIE M ON S.NAME = M.STUDIONAME
                                   WHERE M.INCOLOR='N')
ORDER BY S.ADDRESS;

SELECT NAME, ADDRESS, AVG(LENGTH) AS AVG_LEN
FROM STUDIO S LEFT JOIN MOVIE M ON S.NAME = M.STUDIONAME
GROUP BY NAME, ADDRESS
HAVING COUNT(TITLE) <= 3