SELECT S.CLASS, MIN(YEAR(DATE)) AS MIN, MAX(YEAR(DATE)) AS MAX, COUNT(DISTINCT B.NAME) AS CNT
FROM SHIPS S LEFT JOIN OUTCOMES O ON S.NAME = O.SHIP
LEFT JOIN BATTLES B ON O.BATTLE = B.NAME 
WHERE S.CLASS LIKE 'N%'
GROUP BY S.CLASS

SELECT T1.BATTLE FROM	
(SELECT O.BATTLE, COUNT(S.NAME) CNT_BB
FROM CLASSES C, SHIPS S, OUTCOMES O
WHERE C.CLASS = S.CLASS AND S.NAME = O.SHIP
AND C.TYPE = 'bb'
GROUP BY O.BATTLE) T1 
JOIN
(SELECT O.BATTLE, COUNT(S.NAME) CNT_BC
FROM CLASSES C, SHIPS S, OUTCOMES O
WHERE C.CLASS = S.CLASS AND S.NAME = O.SHIP
AND C.TYPE = 'bc'
GROUP BY O.BATTLE) T2
ON T1.BATTLE = T2.BATTLE
AND T1.CNT_BB > T2.CNT_BC