SELECT S.NAME, COUNT(M.TITLE) AS CNT
FROM STUDIO S JOIN MOVIE M
ON S.NAME = M.STUDIONAME
GROUP BY S.NAME
HAVING COUNT(M.TITLE) < 2

SELECT NAME FROM MOVIEEXEC
WHERE NETWORTH = (SELECT MIN(NETWORTH) FROM MOVIEEXEC)

SELECT NAME FROM MOVIEEXEC
WHERE NETWORTH <= ALL(SELECT NETWORTH FROM MOVIEEXEC)