SELECT DISTINCT S.STARNAME, MS.BIRTHDATE
FROM MOVIE M, STARSIN S, MOVIESTAR MS
WHERE M.TITLE = S.MOVIETITLE AND M.YEAR = S.MOVIEYEAR
AND S.STARNAME = MS.NAME
AND S.STARNAME NOT LIKE '%Jr.%'
AND M.INCOLOR = 'Y'
ORDER BY BIRTHDATE DESC, S.STARNAME

SELECT NAME, BIRTHDATE
FROM MOVIESTAR MS
WHERE NAME NOT LIKE '%Jr.%'
AND NAME IN (SELECT STARNAME 
             FROM STARSIN, MOVIE
			 WHERE TITLE = MOVIETITLE AND YEAR = MOVIEYEAR
			 AND INCOLOR = 'Y')
ORDER BY BIRTHDATE DESC, NAME

SELECT NAME, YEAR(MS.BIRTHDATE) AS YEAR, COUNT(DISTINCT M.STUDIONAME) AS CNT
FROM MOVIESTAR MS 
LEFT JOIN STARSIN S ON MS.NAME = S.STARNAME
LEFT JOIN MOVIE M ON M.TITLE = S.MOVIETITLE AND M.YEAR = S.MOVIEYEAR
WHERE MS.GENDER = 'F'
GROUP BY MS.NAME, MS.BIRTHDATE
HAVING COUNT(S.MOVIETITLE) <= 6